### ISSUE TITLE
Add Targeting logic

### ISSUE THREAD

**Issue by arapawa** [dannytpeck/dengue#1]
This way we can upload targeted CIEs, as well as CIEs tied to levels.

**Comment by dannytpeck** [comment]
It's a good feature, but tough to implement. Here's what we have to solve for:

1) Limeade can't accept updates to CIEs with targeting if those CIEs are Requirements on the Levels file
2) Limeade needs multiple copies of the CIE (multiple lines on the CSV file) if those CIEs are targeted by Subgroup
3) Limeade needs a single line with Piped Values if that CIE is using Column-based targeting

#Limeade #AlwaysMakingThingsDifficult

**Comment by dannytpeck** [comment]
First things first, let's build out the Visual side of things, the coding solutions can come later!

**Comment by arapawa** [comment]
Yeah definitely. Limeade prevented me from uploading a CIE that happened to be a required item in a subgrouped program earlier, so it would be nice to solve eventually.

I'm definitely down to solve for visual stuff first. I've got some ideas, but didn't see a need to note them as issues for some reason.

**Comment by arapawa** [comment]
Should we Close this issue for now?

**Comment by dannytpeck** [comment]
Targeting will now be pulled in and is visible in a readonly input so at least now we can tell if the CIE _has_ targeting and see right away if we can use the app to edit it!
