### ISSUE TITLE
Add ability to change image (URL)

### ISSUE THREAD

**Issue by arapawa** [dannytpeck/dengue#4]
Add functionality similar to content-editing, for changing a CIE's image. Although the user will still need to load the image into Limeade, it will alleviate the need to download, edit, and upload .csvs simply to change an image (or while part of other updates to the CIE).

1. Make action to edit image (double-click?), image preview changes to text-field with URL.
2. From there the user can input a new image URL.
3. Then the user can double-click (or otherwise) to preview the image.
4. The user can then upload the changes as normal.

**Comment by arapawa** [comment]
I can try to tackle this one. It sounds like a challenge I'd enjoy. 😄

**Comment by dannytpeck** [comment]
@arapawa I am All About you trying this one, but hit me up if you have any issues!

**Comment by arapawa** [comment]
Resolved with https://github.com/dannytpeck/dengue/pull/7
